config/routes.rb
Rails.application.routes.draw do
  get 'lists/index'
  get 'lists/show'
  get 'lists/new'
  get 'lists/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "lists#index"

  # GET /lists → lists#index

  # GET /lists/:id → lists#show

  # GET /lists/new → lists#new

  # POST /lists → lists#create

  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: :create
  end

  resources :bookmarks, only: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }

  belongs_to :movie
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :image_url, presence: true

  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @list = List.new
  end

  #def new
    # não existe porque a pagina new não existe, o form está na pagina inicial junto com index
  #end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to lists_path
    else
      @lists = List.all
      render :index, status: :unprocessable_entity
    end
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  private

  def list_params
    params.require(:list).permit(:name, :image_url)
    # params.require(:nomeDoModel).permit(:camposQuePermiteAcesso)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path('bannermovie.png') %>);">
  <div class="container">
    <h1>My <strong>Watch</strong> List</h1>
    <p>List your favorite movies here.</p>
    <a class="btn btn-flat" href="#">Create a List</a>
  </div>
</div>

<div class="container mt-4">

<div class="cards">
  <% @lists.each do | list | %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.image_url %>)">
    <%= link_to list.name, list_path(list) %>
  </div>
  <% end %>

  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Create a New List</h5>
      <%= simple_form_for @list do |f| %>
        <%= f.input :name %>
        <%= f.input :image_url %>
        <%= f.submit "Create", class: "btn btn-primary" %>
      <% end %>
    </div>

  </div>

</div>

</div>

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<p>Find me in app/views/lists/new.html.erb</p>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @list.image_url %>);">
  <div class="container">
    <h1> <%= @list.name %> </h1>
  </div>
</div>

<div class="container mt-4">
  <div class="cards">
    <% @list.bookmarks.each do | bookmark | %>
      <div class="card-product">
        <%= image_tag bookmark.movie.poster_url %>
        <div class="card-product-infos">
        <h2> <%= bookmark.movie.title %> (<%= bookmark.movie.rating %>)</h2>
        <p><%= bookmark.comment %></p>
        <p><%= link_to "Remove", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you Sure?"}, class: "text-danger" %></p>
      </div>
    </div>
    <% end  %>
  </div>
</div>

<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-4">
      <div class="card">
        <div class="card-body">
            <h5 class="card-title">Add a Movie to List</h5>
            <%= simple_form_for [@list, @bookmark] do |f| %>
              <%= f.association :movie, collection: Movie.all %>
              <%= f.input :comment %>
              <div class="d-grid">
              <%= f.submit "Add Movie", class: 'btn btn-primary' %>
              </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>